name: Test

on:
  push:
  pull_request:
  workflow_dispatch: # add manually button

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run Gradle
        run: ./gradlew run
